plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.dagger.hilt.android'
    id 'kotlin-kapt'
}

apply from: "${rootDir}/common.gradle"

android {
    namespace 'com.git.libraries.network'
}

dependencies {
    implementation libs.coroutines
    implementation libs.hilt.android
    implementation libs.bundles.networking
    kapt libs.hilt.compiler
    kapt libs.moshi.kotlin.codegen
}
